language: node_js
node_js:
  - v17
  - v16
  - v14
  - v12
  - v10
  - v8
  - v6
  - v4
<<<<<<< HEAD
=======
after_script: cat ./coverage/lcov.info | coveralls
>>>>>>> 2f11b0aa35094ec9521863cf44a25ef1717cfb7f
