export const listData = {
    "CategoryID": 2,
    "tagUp": {
        "layout": "RelativeLayout",
        "nme": "热门地标周边酒店",
        "itemLst": [{
            "nme": "还没想好周末去哪玩？",
            "lnk": "http://hotels.ctrip.com/around",
            "isHot": "N"
        }]
    },
    "tagDown": {
        "layout": "LinearLayout",
        "nme": "促销",
        "itemLst": [{
            "nme": "全国火车站周边酒店8折起",
            "lnk": "https://hotels.ctrip.com/webapp/hotelevents/plist/dibiaohuochezhanzhoubian",
            "isHot": "N"
        }, {
            "nme": "全国机场周边酒店8折起",
            "lnk": "https://hotels.ctrip.com/webapp/hotelevents/plist/jichangzhoubianjiudiantuijian",
            "isHot": "N"
        }, {
            "nme": "百城千店 优选酒店80元起",
            "lnk": "https://hotels.ctrip.com/webapp/hotelevents/plist/baodibaichengqiandian",
            "isHot": "N"
        }]
    },
    "exNme": "更多国内酒店",
    "exLnk": "http://hotels.ctrip.com/",
    "prdLst": [{
        "isStarLicense": true,
        "score": 4.7,
        "star": 5,
        "rstar": 6,
        "nme": "成都城市名人酒店",
        "img": "//dimg11.c-ctrip.com/images/200c1a000001901vm01D9_R_300_120.jpg",
        "count": 0,
        "lnk": "http://hotels.ctrip.com/hotel/435194.html",
        "isStar": true,
        "starTyp": 0,
        "zoneLst": [{
            "typ": "Zone",
            "nme": "天府广场/盐市口商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone189"
        }, {
            "typ": "Zone",
            "nme": "春熙路/太古里商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone187"
        }],
        "commt": 7347,
        "cusEval": 5,
        "price": {
            "isShowVipPrice": false,
            "currency": "RMB",
            "amt": 545,
            "isVip": false,
            "typ": "min"
        },
        "commtLnk": "http://hotels.ctrip.com/hotel/dianping/435194.html#ctm_ref"
    }, {
        "isStarLicense": false,
        "score": 4.8,
        "star": 5,
        "rstar": 6,
        "nme": "成都万达瑞华酒店",
        "img": "//dimg11.c-ctrip.com/images/200c0j000000aweqfC96E_R_300_120.jpg",
        "count": 0,
        "lnk": "http://hotels.ctrip.com/hotel/3455825.html",
        "isStar": false,
        "starTyp": 0,
        "zoneLst": [{
            "typ": "Zone",
            "nme": "天府广场/盐市口商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone189"
        }, {
            "typ": "Zone",
            "nme": "春熙路/太古里商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone187"
        }],
        "commt": 7939,
        "cusEval": 5.5,
        "price": {
            "isShowVipPrice": false,
            "currency": "RMB",
            "amt": 929,
            "isVip": false,
            "typ": "min"
        },
        "commtLnk": "http://hotels.ctrip.com/hotel/dianping/3455825.html#ctm_ref"
    }, {
        "isStarLicense": true,
        "score": 4.8,
        "star": 4,
        "rstar": 6,
        "nme": "成都瑞城名人酒店",
        "img": "//dimg11.c-ctrip.com/images/200m1e000001fvyd2AB3D_R_300_120.jpg",
        "count": 0,
        "lnk": "http://hotels.ctrip.com/hotel/470094.html",
        "isStar": true,
        "starTyp": 0,
        "zoneLst": [{
            "typ": "Zone",
            "nme": "文殊院/龙湖上城天街",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone188"
        }, {
            "typ": "Zone",
            "nme": "天府广场/盐市口商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone189"
        }],
        "commt": 19479,
        "cusEval": 5,
        "price": {
            "isShowVipPrice": false,
            "currency": "RMB",
            "amt": 307,
            "isVip": false,
            "typ": "min"
        },
        "commtLnk": "http://hotels.ctrip.com/hotel/dianping/470094.html#ctm_ref"
    }, {
        "isStarLicense": false,
        "score": 4.8,
        "star": 5,
        "rstar": 6,
        "nme": "成都瑯珀·凯悦臻选酒店",
        "img": "//dimg11.c-ctrip.com/images/0205p120008pce6vuB2FC_R_300_120.jpg",
        "count": 0,
        "lnk": "http://hotels.ctrip.com/hotel/70991019.html",
        "isStar": false,
        "starTyp": 0,
        "zoneLst": [{
            "typ": "Zone",
            "nme": "春熙路/太古里商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone187"
        }, {
            "typ": "Zone",
            "nme": "天府广场/盐市口商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone189"
        }],
        "commt": 1549,
        "cusEval": 4.5,
        "price": {
            "isShowVipPrice": false,
            "currency": "RMB",
            "amt": 1006,
            "isVip": false,
            "typ": "min"
        },
        "commtLnk": "http://hotels.ctrip.com/hotel/dianping/70991019.html#ctm_ref"
    }, {
        "isStarLicense": false,
        "score": 4.8,
        "star": 4,
        "rstar": 6,
        "nme": "月牙濠璟酒店（成都宽窄巷子店）",
        "img": "//dimg11.c-ctrip.com/images/0204k120008yo2wn0DA72_R_300_120.jpg",
        "count": 0,
        "lnk": "http://hotels.ctrip.com/hotel/512786.html",
        "isStar": false,
        "starTyp": 0,
        "zoneLst": [{
            "typ": "Zone",
            "nme": "金沙遗址/一品天下",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone675"
        }, {
            "typ": "Zone",
            "nme": "宽窄巷子/中医学院附近地区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone1162"
        }],
        "commt": 2820,
        "cusEval": 3.5,
        "price": {
            "isShowVipPrice": false,
            "currency": "RMB",
            "amt": 282,
            "isVip": false,
            "typ": "min"
        },
        "commtLnk": "http://hotels.ctrip.com/hotel/dianping/512786.html#ctm_ref"
    }, {
        "isStarLicense": false,
        "score": 4.8,
        "star": 4,
        "rstar": 6,
        "nme": "中建·锦江都城酒店（成都春熙路太古里店）",
        "img": "//dimg11.c-ctrip.com/images/0203d1200095kjzqtA6E5_R_300_120.png",
        "count": 0,
        "lnk": "http://hotels.ctrip.com/hotel/75425110.html",
        "isStar": false,
        "starTyp": 0,
        "zoneLst": [{
            "typ": "Zone",
            "nme": "天府广场/盐市口商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone189"
        }, {
            "typ": "Zone",
            "nme": "春熙路/太古里商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone187"
        }],
        "commt": 683,
        "cusEval": 3.5,
        "price": {
            "isShowVipPrice": false,
            "currency": "RMB",
            "amt": 479,
            "isVip": false,
            "typ": "min"
        },
        "commtLnk": "http://hotels.ctrip.com/hotel/dianping/75425110.html#ctm_ref"
    }, {
        "isStarLicense": false,
        "score": 4.8,
        "star": 4,
        "rstar": 6,
        "nme": "来住H·HOTEL(成都太古里九眼桥店)",
        "img": "//dimg11.c-ctrip.com/images/200212000000sx46r1364_R_300_120.jpg",
        "count": 0,
        "lnk": "http://hotels.ctrip.com/hotel/23755233.html",
        "isStar": false,
        "starTyp": 0,
        "zoneLst": [{
            "typ": "Zone",
            "nme": "万象城/水碾河",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone677"
        }, {
            "typ": "Zone",
            "nme": "春熙路/太古里商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone187"
        }],
        "commt": 13371,
        "cusEval": 4.5,
        "price": {
            "isShowVipPrice": false,
            "currency": "RMB",
            "amt": 242,
            "isVip": false,
            "typ": "min"
        },
        "commtLnk": "http://hotels.ctrip.com/hotel/dianping/23755233.html#ctm_ref"
    }, {
        "isStarLicense": true,
        "score": 4.7,
        "star": 5,
        "rstar": 6,
        "nme": "四川岷山饭店",
        "img": "//dimg11.c-ctrip.com/images/220j1b000001ap6vw1096_R_300_120.jpg",
        "count": 0,
        "lnk": "http://hotels.ctrip.com/hotel/391650.html",
        "isStar": true,
        "starTyp": 0,
        "zoneLst": [{
            "typ": "Zone",
            "nme": "天府广场/盐市口商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone189"
        }, {
            "typ": "Zone",
            "nme": "春熙路/太古里商业区",
            "lnk": "http://hotels.ctrip.com/hotel/Chengdu28/zone187"
        }],
        "commt": 4305,
        "cusEval": 5,
        "price": {
            "isShowVipPrice": false,
            "currency": "RMB",
            "amt": 374,
            "isVip": false,
            "typ": "min"
        },
        "commtLnk": "http://hotels.ctrip.com/hotel/dianping/391650.html#ctm_ref"
    }],
    "tabs": [{
        "pinyin": "BeiJing",
        "tabNme": "北京"
    }, {
        "pinyin": "ShangHai",
        "tabNme": "上海"
    }, {
        "pinyin": "GuangZhou",
        "tabNme": "广州"
    }, {
        "pinyin": "ChengDu",
        "tabNme": "成都"
    }, {
        "pinyin": "ShenZhen",
        "tabNme": "深圳"
    }, {
        "pinyin": "HangZhou",
        "tabNme": "杭州"
    }, {
        "pinyin": "ChangChun",
        "tabNme": "长春"
    }, {
        "pinyin": "ChangSha",
        "tabNme": "长沙"
    }, {
        "pinyin": "ZhongQing",
        "tabNme": "重庆"
    }, {
        "pinyin": "DaLian",
        "tabNme": "大连"
    }, {
        "pinyin": "FuZhou",
        "tabNme": "福州"
    }, {
        "pinyin": "GuiYang",
        "tabNme": "贵阳"
    }, {
        "pinyin": "GuiLin",
        "tabNme": "桂林"
    }, {
        "pinyin": "HuangShan",
        "tabNme": "黄山"
    }, {
        "pinyin": "HaErBin",
        "tabNme": "哈尔滨"
    }],
    "adLst": []
}